version: '3.1'

services:

  db:
    container_name: postgres
    build:
      context: ./../postgres
      dockerfile: ../docker/postgres/postgres.dockerfile
    ports:
      - 5432:5432
    restart: always